"""Summarise the training-data composition into a model card.

Reads one or more VoiceShield v2 JSONL files (synthetic, external, and/or real
donated cases) and emits:
  - model_card.json  : machine-readable composition + sources
  - a printed TS snapshot suitable for mobile/src/data/modelManifest.ts

This is what the app surfaces on the "Data & Model" screen so users can see
exactly what data any model was trained on. The live detector is the rule
engine; the ML baseline is experimental and disclosed here honestly.

Usage:
    python ml/model_card.py ml/artifacts/synthetic.jsonl [more.jsonl ...] \
        --model-version 0.1.0-baseline --out ml/artifacts/model_card.json
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import date
from pathlib import Path

SOURCE_INFO = {
    "synthetic": "Synthetic RU/KZ scripts generated from the scheme taxonomy (not real calls)",
    "teleantifraud": "TeleAntiFraud-28k telecom-fraud corpus (transfer only)",
    "korccvi": "Korean voice-phishing transcripts (transfer only)",
    "sms_scam": "SMS Scam Detection merged, Kaggle (transfer only)",
    "manual": "Reviewer-labelled cases entered in the app",
    "live": "User-donated live calls (redacted, consented)",
    "import": "Imported cases (untrusted until reviewed)",
}


def summarise(paths: list[Path]) -> dict:
    labels: Counter = Counter()
    origins: Counter = Counter()
    langs: Counter = Counter()
    schemes: Counter = Counter()
    total = 0
    trusted = 0
    for path in paths:
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            total += 1
            labels[row.get("label", "unknown")] += 1
            prov = row.get("provenance") or {}
            origins[prov.get("origin", "unknown")] += 1
            trusted += 1 if prov.get("trusted") else 0
            langs[row.get("lang", "unknown")] += 1
            schemes[row.get("scheme", "unknown")] += 1
    return {
        "total": total,
        "trustedReal": trusted,
        "byLabel": dict(labels),
        "byOrigin": dict(origins),
        "byLanguage": dict(langs),
        "byScheme": dict(schemes),
    }


def build_card(paths: list[Path], model_version: str) -> dict:
    comp = summarise(paths)
    sources = [
        {"origin": origin, "count": count, "description": SOURCE_INFO.get(origin, origin)}
        for origin, count in sorted(comp["byOrigin"].items(), key=lambda kv: -kv[1])
    ]
    return {
        "schemaVersion": "voiceshield.modelcard.v1",
        "generatedAt": date.today().isoformat(),
        "modelVersion": model_version,
        "status": "experimental",
        "liveDetector": "deterministic rule engine (not machine-learned; not trained on user calls)",
        "composition": comp,
        "sources": sources,
        "caveats": [
            "Synthetic and external rows are transfer/pretraining only and are excluded from the trusted evaluation set.",
            "Held-out evaluation requires real, reviewer-labelled RU/KZ calls.",
            "This model is not used for live decisions until an independent RU/KZ evaluation passes.",
        ],
    }


def ts_snapshot(card: dict) -> str:
    comp = card["composition"]
    return (
        "// AUTO-GENERATED by ml/model_card.py — do not hand-edit the numbers.\n"
        "export const trainingDataSnapshot = " + json.dumps({
            "generatedAt": card["generatedAt"],
            "modelVersion": card["modelVersion"],
            "total": comp["total"],
            "trustedReal": comp["trustedReal"],
            "byOrigin": comp["byOrigin"],
            "byLabel": comp["byLabel"],
            "byLanguage": comp["byLanguage"],
        }, ensure_ascii=False, indent=2) + " as const\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a VoiceShield model card from v2 JSONL data")
    parser.add_argument("paths", nargs="+", type=Path)
    parser.add_argument("--model-version", default="0.1.0-baseline")
    parser.add_argument("--out", type=Path, default=Path("ml/artifacts/model_card.json"))
    parser.add_argument("--ts-out", type=Path, help="Optional: write the mobile TS snapshot here")
    args = parser.parse_args()

    card = build_card(args.paths, args.model_version)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(card, ensure_ascii=False, indent=2), encoding="utf-8")
    if args.ts_out:
        args.ts_out.write_text(ts_snapshot(card), encoding="utf-8")
    print(json.dumps({"out": str(args.out), "total": card["composition"]["total"], "sources": len(card["sources"])}))


if __name__ == "__main__":
    main()
