import type { I18nKeys } from './ru'

export const en: I18nKeys = {
  app: { name: 'KZ VoiceShield', tagline: 'Protection from phone fraud' },
  nav: { live: 'Protect', scan: 'Scan', learn: 'Learn', cases: 'Cases', more: 'More' },
  live: {
    active: 'PROTECTION ACTIVE', standby: 'STANDBY MODE', start: 'Start protection', stop: 'Stop', saveCase: 'Save case', shareReport: 'Report', transcript: 'LIVE TRANSCRIPT', waitAudio: 'WAITING FOR AUDIO', hearsAudio: 'MICROPHONE HEARS AUDIO', pauseTitle: 'Take a 30-second pause', pauseCopy: 'End the call. Do not share codes or approve payments.', startPause: 'Start pause', restartPause: 'Restart pause', signals: 'signals', correction: 'AI correction applied', rawDisagreement: 'Raw and corrected difference: {from} → {to}', noCaption: 'No caption text?', microphoneFallback: 'Use microphone and speaker', endCall: 'End call', sharedData: 'I shared data', recoveryPlan: 'Urgent recovery plan', practice: 'Practice', scamPatterns: 'Learn scam patterns', doThisNow: 'Do this now', liveTranscript: 'LIVE TRANSCRIPT', microphoneState: 'MICROPHONE HEARS AUDIO', confidence: 'confidence', capture: 'capture coverage', limitedEvidence: 'There is not enough evidence for a confident conclusion. Do not share codes or money until you verify the caller through an official channel.', waitingSpeaker: 'WAITING FOR AUDIO', transcriptPlaceholder: 'Text will appear here. You can also paste a conversation.', save: 'Save', endCallTitle: 'End the current call?', endCallCopy: 'The current call will be disconnected. End it only when you are ready to stop the conversation.',
  },
  risk: { critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low' },
  setup: {
    title: 'Setup', theme: 'Appearance', themeAuto: 'Auto', themeLight: 'Light', themeDark: 'Dark', language: 'Language', download: 'Download model', deleteAll: 'Delete all data', confirmDelete: 'Confirm deletion', cancel: 'Cancel', privacyTitle: 'Consent is required before protection starts', privacyAccepted: 'Local protection consent accepted', privacyCopy: 'VoiceShield processes call captions, microphone audio, active apps and notification types only during an active session. Notification text, codes and raw numbers are not stored. Saved cases are redacted and encrypted on the device. Local mode does not send audio or transcripts.', agree: 'I agree', notNow: 'Not now', requiredAccess: 'Required access', accessibility: 'Android caption service', captionSettings: 'Android caption settings', riskOverlay: 'Risk overlay', callScreening: 'Call screening role', microphone: 'Microphone fallback', notification: 'Protection notifications', otpDetection: 'Notification access for OTP', battery: 'Battery optimization exemption', xiaomiAutostart: 'Xiaomi/HyperOS autostart', open: 'Open', optionalIntegration: 'Phone integration', optionalCopy: 'As the phone app, VoiceShield can show its own incoming and active SIM-call screen with number risk and family labels. The caller does not need this app. Android does not provide third-party apps with the other caller\'s raw call audio, so transcription uses captions or the microphone.', defaultPhone: 'Use VoiceShield as phone app', defaultPhoneApps: 'Default phone apps', speechModel: 'On-device speech model', speechCopy: 'Recognition runs on the device. The recommendation considers free space, temporary download space and RAM. Downloads resume after network interruptions, and models are checked by size and SHA-256.', recommended: 'Recommended', checkingStorage: 'checking storage…', automatic: 'Automatic recommendation', automaticCopy: 'Uses the best compatible model: {model}', readyForDevice: 'Fits this device · {gb} GB required during download', unavailable: 'Unavailable · requires {gb} GB and {ram} GB RAM', localData: 'Local data', encryptedCases: '{count} encrypted cases.', openAppSettings: 'Open Android app settings', aiAssistant: 'AI assistant', aiCopy: 'Local model for transcript analysis. Downloaded once.', modelDownload: 'Download model', downloading: 'Downloading: {progress}%', ready: 'Ready', setupStatus: 'Configure',
  },
  llm: { title: 'VoiceShield AI', notLoaded: 'AI model is not loaded', loadModel: 'Load model' },
  sms: { title: 'SMS scanner', scan: 'Scan' }, history: { title: 'Call history', clear: 'Clear', empty: 'No saved calls' }, stats: { title: 'Statistics' },
  onboarding: { welcome: 'WELCOME', welcomeTitle: 'Your AI shield\nagainst phone fraud', welcomeBody: 'KZ VoiceShield detects fraud in real time. Speech recognition and rules run on the device.', how: 'HOW IT WORKS', howTitle: 'Speak, listen,\nreceive warnings', howBody: 'Start protection during a suspicious call. The microphone turns the conversation into text and the risk engine analyses every phrase.', important: 'IMPORTANT', importantTitle: 'Turn on speakerphone\nfor both sides', importantBody: 'Android does not allow apps to read internal call audio. Turn on speakerphone so the microphone can hear the other person.', privacy: 'PRIVACY', privacyTitle: 'Local by default,\ncloud only with consent', privacyBody: 'Transcripts are encrypted on the device. Cloud models receive only redacted text after separate consent.', next: 'Next', skip: 'Skip', getStarted: 'Get started' },
}
