// AUTO-GENERATED by ml/model_card.py — do not hand-edit the numbers.
export const trainingDataSnapshot = {
  "generatedAt": "2026-07-11",
  "modelVersion": "0.1.0-baseline",
  "total": 176,
  "trustedReal": 0,
  "byOrigin": {
    "synthetic": 176
  },
  "byLabel": {
    "false_positive": 80,
    "true_positive": 96
  },
  "byLanguage": {
    "ru": 86,
    "kz": 90
  }
} as const
